package types

// QueryGetItem ...
const QueryGetItem = "get-item"

// QueryGetItems ...
const QueryGetItems = "get-items"

// QueryGetBlockHash ...
const QueryGetBlockHash = "get-BlockHash"

// QueryGetOperatorPubkey ...
const QueryGetOperatorPubkey = "get-OperatorPubkey"
